config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :events
  resources :swimmers
  resources :swimmer_events
  resources :teams do
    resources :swimmers, only: [:index, :new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  post '/events/filter' => 'events#filter'
  #patch '/swimmer_events/:id' => 'swimmer_events#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :swimmer_events
  has_many :swimmers, through: :swimmer_events, dependent: :destroy

  validates :name, presence: true, uniqueness: true 
  validates :distance, presence: true
  validates :stroke, presence: true

  scope :filter_by_distance, ->(distance) {where("distance <= ?", distance)}
  scope :filter_by_stroke, ->(stroke) {where("stroke = ?", stroke.downcase)}

  def self.sort
    sorted_events = Event.all.sort_by { |event| event.distance }
  end

end

app/models/swimmer.rb
class Swimmer < ApplicationRecord
  has_secure_password

  validates :name, presence: true 
  validates :email, presence: true, uniqueness: true

  belongs_to :team
  has_many :swimmer_events
  has_many :events, through: :swimmer_events, dependent: :destroy
  # can remove
  accepts_nested_attributes_for :events

  def events_attributes=(events_attributes)
    events_attributes.values.each do |event_attribute|
      if event_attribute[:name] != "" || event_attribute[:distance] != "" || event_attribute[:stroke] != ""
        event = Event.find_or_create_by(event_attribute)
        self.events << event
      end
    end
  end

  # help from https://medium.com/@kaileegray/adding-omniauth-to-rails-web-app-2491392787fa
  def self.find_or_create_by_omniauth(auth)
    oauth_name = auth["info"]["name"]
    oauth_email = auth["info"]["email"] 
    @swimmer = self.find_by(email: oauth_email)
    if !@swimmer 
      @swimmer = self.new(name: oauth_name, email: oauth_email, password: "password", team_id: "4")
      if @swimmer.valid?
        @swimmer.save
      end
    end
    @swimmer
  end

  # not needed, relationship already exists
  def get_events_and_times
    data = []
    self.swimmer_events.each do |swimmer_event|
      event_name = Event.find(swimmer_event.event_id).name
      data_hash = {
        :name => event_name,
        :time => swimmer_event.personal_record,
        :id => swimmer_event.id
      }
      data << data_hash
    end
    data
  end

end

app/models/swimmer_event.rb
class SwimmerEvent < ApplicationRecord
  belongs_to :swimmer 
  belongs_to :event 
end

app/models/swimmer_events.rb
class SwimmerEvents < ApplicationRecord
  belongs_to :swimmer 
  belongs_to :event 
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :swimmers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_swimmer
    @current_swimmer ||= Swimmer.find(session[:user_id]) if session[:user_id]
  end

  def require_login 
    return head(:forbidden) unless session.include? :user_id 
  end

  helper_method :require_login
  helper_method :current_swimmer
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login

  def new 
    @event = Event.new
  end

  def filter
    if params[:filter_type] == "All Events"
      @events = Event.sort
    elsif params[:filter_type] == "By Distance"
      @events = Event.filter_by_distance(params[:filter_value])
      puts @events
    elsif params[:filter_type] == "By Stroke"
      @events = Event.filter_by_stroke(params[:filter_value])
    end
    render :index
  end

  def index
    @events = Event.sort 
  end

  def show 
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.valid?
      @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.valid?
      redirect_to events_path
    else
      render :edit
    end
  end 

  def destroy
    
    Event.find(params[:id]).destroy 
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :distance,
      :stroke
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth 
      @swimmer = Swimmer.find_or_create_by_omniauth(auth)
      session[:user_id] = @swimmer.id
      redirect_to swimmer_path(@swimmer.id)
    else
      swimmer = Swimmer.find_by(email: params[:email])
      if !swimmer
        flash[:notice] = "Account not found."
        return redirect_to '/'
      end
      return head(:forbidden) unless swimmer.authenticate(params[:password])
      session[:user_id] = swimmer.id 
      session[:user_type] = "swimmer"
      redirect_to swimmer_path(swimmer.id)
    end
  end

  def destroy
    session.delete :user_id 
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
  
end

app/controllers/swimmer_events_controller.rb
class SwimmerEventsController < ApplicationController
   
  def update
    puts "here"
    @se = SwimmerEvent.find(params[:id])
    if @se
      @se.update(personal_record: params[:swimmer_event][:personal_record])
      redirect_to swimmer_path(@se.swimmer_id)
    end
    # find_by_id vs find -> errors
  end
  
end

app/controllers/swimmers_controller.rb
class SwimmersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def index
    if params[:team_id]
      @swimmers = Team.find(params[:team_id]).swimmers 
    else
      @swimmers = Swimmer.all 
    end
  end

  def new
    if session[:user_id] && !params[:team_id]
      redirect_to swimmer_path(session[:user_id])
    end
    @swimmer = Swimmer.new 
    @team_id = params[:team_id]
  end

  def create 
    @swimmer = Swimmer.new(swimmer_params)
    if @swimmer.valid?
      @swimmer.save
      # address render issue
      if params[:swimmer][:team_id] == "4"
        session[:user_id] = @swimmer.id
        session[:user_type] = "swimmer"
        redirect_to swimmer_path(@swimmer.id)
      else 
        redirect_to team_path(params[:swimmer][:team_id])
      end
    else
      render :new
    end

  end

  def show
    @swimmer = Swimmer.find(params[:id])
    if !authenticate_user(@swimmer.id)
      return head(:forbidden) 
    end
  end

  def edit
    @swimmer = Swimmer.find(params[:id])
    if !authenticate_user(@swimmer.id)
      return head(:forbidden) 
    end
  end

  def update
    @swimmer = Swimmer.find(params[:id])
    if !authenticate_user(@swimmer.id)
      return head(:forbidden) 
    end
    @swimmer.update(swimmer_params)
    if @swimmer.valid?
      redirect_to swimmer_path(@swimmer.id)
    else
      puts "invalid"
      render :edit
    end
  end

  private

    def swimmer_params
      params.require(:swimmer).permit(
        :name,
        :password,
        :email,
        :team_id,
        event_ids:[],
        events_attributes: [:name, :distance, :stroke]
      )
    end

    def authenticate_user(id)
      id == session[:user_id]
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :require_login

  def index
    @teams = Team.all 
  end

  def show
    @team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
    if session[:user_type] != 'coach' || !authorized?(@team)
      return head(:forbidden)
    end
  end

  def update
    @team = Team.find(params[:id])
    if session[:user_type] != 'coach' || !authorized?(@team)
      return head(:forbidden)
    end
    @team.update(team_params)
    redirect_to team_path(@team.id)
  end 

  private

  def team_params
    params.require(:team).permit(
      :name,
      :hq
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    if session[:user_id]
      redirect_to swimmer_path(session[:user_id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/swimmers_helper.rb
module SwimmersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <%= f.label "Name"%><br>
  <%= f.text_field :name %><br>

  <%= f.label "Distance" %><br>
  <%= f.text_field :distance %><br>

  <%= f.label "Stroke" %><br>
  <%= f.text_field :stroke %><br>
  
  <%= f.submit value="Submit" %>
<% end %>

app/views/events/edit.html.erb
<h1>event/edit</h1>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being edited:
    </h2>
 
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events</h1><br>
<%= form_tag "/events/filter", method: 'post' do %>
  <%= select_tag "filter_type", options_for_select(["All Events", "By Distance", "By Stroke"]) %>
  <input type="text" name="filter_value"><br>
  <input class="normal_button" type="submit" value="Filter">
<% end %><br><br>
  

<% @events.each do |event| %>
  <div class="event_card">
    <p style="font-size: 1.3em"><a href=<%= event_path(event) %> /><%= event.name %></p>
    <% if event.stroke == "freestyle" %>
      <img src="https://i.imgur.com/vKE57Vm.jpg">
    <% elsif event.stroke == "breaststroke" %>
      <img src="https://i.imgur.com/JR51SU3.jpg">
    <% elsif event.stroke == "backstroke" %>
      <img src="https://i.imgur.com/VBbdzdP.jpg">
    <% else %>
      <img src="https://i.imgur.com/CKgE6Le.jpg">
    <% end %>
    <%= button_to "Edit", edit_event_path(event.id), class:"edit_button", method: "get" %>
    <%= form_tag event_path(event.id), method: 'delete' do %>
      <input class="delete_button" type="submit" id="submit" value="Delete"><br>
    <% end %>
  </div>
<% end %>

<%= button_to "Add New Event", new_event_path, class: "normal_button", method: 'get' %><br>

app/views/events/new.html.erb
<h1>New Event</h1>
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being created:
    </h2>
 
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/events/show.html.erb
# event, all swimmers that compete, if time, display

#group by swimmer + time
<h1><%= @event.name %></h1>

# call method from event model to pass data
<ul>
<% @event.swimmer_events.each do |swimmer_event| %>
  <li><%= swimmer_event.swimmer.name %></li>
  <% if swimmer_event.personal_record %>
  <li><%= swimmer_event.personal_record %></li>
  <% end %>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freestyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Ultra" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body background="https://cdn.swimswam.com/wp-content/uploads/2018/03/stock-by-Mike-Lewis-LDM_1946-2.jpg"> 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Freestyle</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if current_swimmer %>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/events">Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/teams">Teams</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/swimmers">Swimmers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "My Account", edit_swimmer_path(current_swimmer.id) %>
          </li>
          <li class="nav-item">
             <%= form_tag logout_path, method: 'post' do %>
              <button class="btn btn-link nav-link" type="submit">Log Out</button>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item active">
            <a class="nav-link" href="/login">Log In<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/swimmers/new">Sign Up<span class="sr-only">(current)</span></a>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/swimmers/_form.html.erb
<%= form_for @swimmer do |f| %>

  <!-- swimmer info -->
  <%= f.label :name, "Name", class:"form_heading" %><br>
  <%= f.text_field :name %><br>

  <%= f.label :name, "Email", class:"form_heading" %><br>
  <%= f.text_field :email %><br>

  <%= f.label :name, "Password", class:"form_heading" %><br>
  <%= f.password_field :password %><br><br>
  
  <!-- choose a team  -->
  <%= f.label :name, "Team", class:"form_heading"  %><br>
  <%= f.collection_select :team_id, Team.all, :id, :name %><br><br>

  <!-- choose events -->
  <%= f.label :name, "Events", class:"form_heading"  %>
  <%= f.collection_check_boxes(:event_ids, Event.sort, :id, :name) do |b| %><br>
    <%= b.label(class:"checkbox") { b.check_box + b.text } %>
  <% end %><br><br>
  <%= f.label :name, "New Event (Optional)", class:"form_heading"  %><br>
  <%= f.fields_for :events, @swimmer.events.build do |events_fields| %>
    <label>Name</label><br>
    <%= events_fields.text_field :name %><br>
    <label>Distance</label><br>
    <%= events_fields.text_field :distance %><br>
    <label>Stroke</label><br>
    <%= events_fields.text_field :stroke %><br>
  <% end %><br>


  <%= f.submit value="Submit", class:"normal_button" %>
<% end %>

app/views/swimmers/edit.html.erb
<h1>Update Account</h1><br>
<% if @swimmer.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@swimmer.errors.count, "error") %>
      prohibited this account from being updated:
    </h2>
 
    <ul>
    <% @swimmer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/swimmers/index.html.erb
<h1>Swimmers</h1><br>
<% @swimmers.each do |swimmer| %>
  <h5><%= swimmer.name %> - <%= swimmer.email %></h5>
  <br>
<% end %>

app/views/swimmers/new.html.erb
<h1>Sign Up</h1>
<% if @swimmer.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@swimmer.errors.count, "error") %>
      prohibited this account from being created:
    </h2>
 
    <ul>
    <% @swimmer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @swimmer do |f| %>

  <!-- swimmer info -->
  <%= f.label :name, "Name", class:"form_heading" %><br>
  <%= f.text_field :name %><br>

  <%= f.label :name, "Email", class:"form_heading" %><br>
  <%= f.text_field :email %><br>

  <%= f.label :name, "Password", class:"form_heading" %><br>
  <%= f.password_field :password %><br><br>
  
  <!-- choose a team  
  <%= f.label :name, "Team", class:"form_heading"  %><br>
  <%= f.collection_select :team_id, Team.all, :id, :name %><br><br>
  -->
  <% if @team_id %>
    <%= f.hidden_field :team_id, value: @team_id %>
  <% else %>
    <%= f.hidden_field :team_id, value: "4" %>
  <% end %>

  <!-- choose events -->
  <%= f.label :name, "Events", class:"form_heading"  %>
  <%= f.collection_check_boxes(:event_ids, Event.sort, :id, :name) do |b| %><br>
    <%= b.label(class:"checkbox") { b.check_box + b.text } %>
  <% end %><br><br>
  <%= f.label :name, "New Event (Optional)", class:"form_heading"  %><br>
  <%= f.fields_for :events, @swimmer.events.build do |events_fields| %>
    <label>Name</label><br>
    <%= events_fields.text_field :name %><br>
    <label>Distance</label><br>
    <%= events_fields.text_field :distance %><br>
    <label>Stroke</label><br>
    <%= events_fields.text_field :stroke %><br>
  <% end %><br>


  <%= f.submit value="Submit", class:"normal_button" %>
<% end %>

app/views/swimmers/show.html.erb
<h1><%= @swimmer.name %></h1><br>
<h3>Team <%= @swimmer.team.name %></h3>
<% if @swimmer.team_id != 4 %>
	<%= button_to "Team Page", team_path(@swimmer.team_id), class: "normal_button", method: 'get' %>
<% end %>
<br>
<h3>My Events</h3>

<!-- example of utilizing rails relationships -->
<% @swimmer.swimmer_events.each do |swim_event|%>
  <h5><%= swim_event.event.name %> - <%= swim_event.personal_record %></h5>
  <%= form_for swim_event do |f| %>
    <%= f.text_field :personal_record %>
    <%= f.submit value="Update Time", class:"normal_button" %><br><br><br>
  <% end %>
<% end %>

app/views/welcome/home.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="banner">
  <div class="brand">Freestyle</div>
  <img class="landing" src="https://cdn.swimswam.com/wp-content/uploads/2014/09/Waikiki-Roughwater-Swim-by-Mike-Lewis-8.jpg">
</div>